### ISSUE TITLE
lifefs-editor creates archive that can't be unpacked with 7z on ubuntu-24.04 LTS

### ISSUE THREAD

**Issue by jw-rav** [mwhudson/livefs-editor#61] opened 2024-08-14 09:15 UTC
```
#! /bin/sh -ex

mkdir /var/tmp/lifefs-edit-test
cd  /var/tmp/lifefs-edit-test

sudo PYTHONPATH=~/repos/subiquity/livefs-editor python3 \
     -m livefs_edit --debug \
     /var/tmp/images/ubuntu-24.04-live-server-amd64.iso \
     my.iso \
     --add-cmdline-arg quiet

7z -y x -bd -bb0 my.iso
```

errors out with

```
ERROR: Dangerous link path was ignored : ubuntu : ./
```

```
7z l my.iso
```
shows a new entry "ubuntu" which was not present in the original .iso.

[https://sourceforge.net/p/sevenzip/bugs/2356/](url) talks about a bug in current 7z concerning symlinks. Guess, this might be the root of the problem.

But why is this symlink created at all when only operation requested is to add a kernel command line option?

**Comment by mwhudson** [comment] 2024-08-15 18:53
I can reproduce this, but the symlink is present in the original ISO too:

```
mwhudson@orcrist:~/tmp/7z/repacked$ sudo mount -r ~/isos/noble/ubuntu-24.04-live-server-amd64.iso ~/tmp/mnt/1
mwhudson@orcrist:~/tmp/7z/repacked$ ls -l ~/tmp/mnt/1/ubuntu
lr-xr-xr-x 1 root root 1 Apr 24 00:44 /home/mwhudson/tmp/mnt/1/ubuntu -> .
```

I don't know why 7z finds it only when repacked, I guess that's some xorriso detail. It's certainly not something livefs_edit is doing.

**Comment by jw-rav** [comment] 2024-08-16 07:55
Yes, the real bug is in 7z, see the link above.

As a workaround, I tried to remove the symlink by

```
--rm new/iso/ubuntu
```

but this won't remove the symlink and even won't give an error message

OTOH,

```
--shell 'rm new/iso/ubuntu'
```
will remove it.

**Comment by mwhudson** [comment] 2024-08-18 21:25
I think I'm going to close this because I don't want to get nerdsniped into debugging 7z and/or xorriso, hope that's OK.

Does https://github.com/mwhudson/livefs-editor/commit/019e5df209af78c05f2f87f0be9cd220ba94e455 help with removing the symlink?

**Closed by mwhudson** 2024-08-18 21:25 UTC

**Comment by jw-rav** [comment] 2024-08-22 09:25
> I think I'm going to close this because I don't want to get nerdsniped into debugging 7z and/or xorriso, hope that's OK.

That's fine.

> Does [019e5df](https://github.com/mwhudson/livefs-editor/commit/019e5df209af78c05f2f87f0be9cd220ba94e455) help with removing the symlink?

Yes. Works for me.

Thanks!
